# Generated by Django 5.2 on 2025-04-07 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('prescription', 'Prescription'), ('diagnostic', 'Diagnostic Report'), ('doctors_note', "Doctor's Note"), ('surgery', 'Surgery/Discharge Summary'), ('other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('encrypted_file', models.FileField(upload_to='records/')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='records/versioned/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.IntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='medical_records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField()),
                ('message', models.CharField(max_length=255)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecord')),
            ],
        ),
    ]
