# Generated by Django 5.2 on 2025-04-08 21:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('prescription', 'Prescription'), ('blood_test', 'Blood Test'), ('diagnostic_report', 'Diagnostic Report'), ('doctor_note', "Doctor's Note"), ('surgery_summary', 'Surgery Summary')], max_length=100)),
                ('description', models.TextField()),
                ('record_file', models.FileField(upload_to='medical_records/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('version_history', models.JSONField(default=list)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_records.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField()),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_records.medicalrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
