# Generated by Django 5.2 on 2025-04-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
