# Generated by Django 5.2 on 2025-04-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ratings', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewflag',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reviews_ratings.review'),
        ),
    ]
