# Generated by Django 5.2 on 2025-04-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_ratings', '0004_rename_created_at_reviewflag_reported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
