# Generated by Django 4.2.20 on 2025-04-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_search', '0002_hospital_treatment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_rate', models.FloatField(help_text='Recovery rate in percentage')),
                ('icu_capacity', models.PositiveIntegerField()),
                ('has_robotic_surgery', models.BooleanField(default=False)),
                ('medical_equipment', models.TextField()),
                ('post_treatment_support', models.TextField()),
                ('accreditation', models.CharField(max_length=255)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_stats', to='hospital_search.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_hospitals', models.ManyToManyField(to='hospital_search.hospital')),
            ],
        ),
    ]
