# Generated by Django 4.2.20 on 2025-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='treatment_type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
